apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: library:1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb+srv://root:A7292080a@cluster0.i78r5.mongodb.net/library?retryWrites=true&w=majority

          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
